import * as protocol from "./protocol.js";
import type { AppServerClient } from "./request-client.js";

export type RequestClientMethodKind = "request" | "notification";
export type RequestClientParamsMode =
  | "none"
  | "omitted"
  | "required"
  | "optional-empty";

export type AppServerRequestClientMethodSpec = {
  name: string;
  method: string;
  kind: RequestClientMethodKind;
  params: RequestClientParamsMode;
};

export const APP_SERVER_REQUEST_CLIENT_METHODS: readonly AppServerRequestClientMethodSpec[] =
  [
    {
      name: "initialize",
      method: protocol.METHOD_INITIALIZE,
      kind: "request",
      params: "required",
    },
    {
      name: "initialized",
      method: protocol.METHOD_INITIALIZED,
      kind: "notification",
      params: "none",
    },
    {
      name: "listCapabilities",
      method: protocol.METHOD_CAPABILITY_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "listSessions",
      method: protocol.METHOD_THREAD_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readThread",
      method: protocol.METHOD_THREAD_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "revertThread",
      method: protocol.METHOD_THREAD_REVERT,
      kind: "request",
      params: "required",
    },
    {
      name: "listThreads",
      method: protocol.METHOD_THREAD_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "moveThreadToSection",
      method: protocol.METHOD_THREAD_SECTION_MOVE,
      kind: "request",
      params: "required",
    },
    {
      name: "listThreadSections",
      method: protocol.METHOD_THREAD_SECTION_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "createThreadSection",
      method: protocol.METHOD_THREAD_SECTION_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateThreadSection",
      method: protocol.METHOD_THREAD_SECTION_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteThreadSection",
      method: protocol.METHOD_THREAD_SECTION_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "listLoadedThreads",
      method: protocol.METHOD_THREAD_LOADED_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "unsubscribeThread",
      method: protocol.METHOD_THREAD_UNSUBSCRIBE,
      kind: "request",
      params: "required",
    },
    {
      name: "incrementThreadElicitation",
      method: protocol.METHOD_THREAD_INCREMENT_ELICITATION,
      kind: "request",
      params: "required",
    },
    {
      name: "decrementThreadElicitation",
      method: protocol.METHOD_THREAD_DECREMENT_ELICITATION,
      kind: "request",
      params: "required",
    },
    {
      name: "approveGuardianDeniedAction",
      method: protocol.METHOD_THREAD_APPROVE_GUARDIAN_DENIED_ACTION,
      kind: "request",
      params: "required",
    },
    {
      name: "injectThreadItems",
      method: protocol.METHOD_THREAD_INJECT_ITEMS,
      kind: "request",
      params: "required",
    },
    {
      name: "archiveThread",
      method: protocol.METHOD_THREAD_ARCHIVE,
      kind: "request",
      params: "required",
    },
    {
      name: "unarchiveThread",
      method: protocol.METHOD_THREAD_UNARCHIVE,
      kind: "request",
      params: "required",
    },
    {
      name: "setThreadName",
      method: protocol.METHOD_THREAD_NAME_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "updateThreadMetadata",
      method: protocol.METHOD_THREAD_METADATA_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "addThreadQueue",
      method: protocol.METHOD_THREAD_QUEUE_ADD,
      kind: "request",
      params: "required",
    },
    {
      name: "listThreadQueue",
      method: protocol.METHOD_THREAD_QUEUE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "updateThreadQueue",
      method: protocol.METHOD_THREAD_QUEUE_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteThreadQueue",
      method: protocol.METHOD_THREAD_QUEUE_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "reorderThreadQueue",
      method: protocol.METHOD_THREAD_QUEUE_REORDER,
      kind: "request",
      params: "required",
    },
    {
      name: "startThreadQueue",
      method: protocol.METHOD_THREAD_QUEUE_START,
      kind: "request",
      params: "required",
    },
    {
      name: "readPromptHistory",
      method: protocol.METHOD_PROMPT_HISTORY_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "appendPromptHistory",
      method: protocol.METHOD_PROMPT_HISTORY_APPEND,
      kind: "request",
      params: "required",
    },
    {
      name: "listThreadTurns",
      method: protocol.METHOD_THREAD_TURNS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listThreadItems",
      method: protocol.METHOD_THREAD_ITEMS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "searchThreads",
      method: protocol.METHOD_THREAD_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "searchThreadOccurrences",
      method: protocol.METHOD_THREAD_SEARCH_OCCURRENCES,
      kind: "request",
      params: "required",
    },
    {
      name: "cleanThreadBackgroundTerminals",
      method: protocol.METHOD_THREAD_BACKGROUND_TERMINALS_CLEAN,
      kind: "request",
      params: "required",
    },
    {
      name: "listThreadBackgroundTerminals",
      method: protocol.METHOD_THREAD_BACKGROUND_TERMINALS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "terminateThreadBackgroundTerminal",
      method: protocol.METHOD_THREAD_BACKGROUND_TERMINALS_TERMINATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateThreadSettings",
      method: protocol.METHOD_THREAD_SETTINGS_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "setThreadMemoryMode",
      method: protocol.METHOD_THREAD_MEMORY_MODE_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "runThreadShellCommand",
      method: protocol.METHOD_THREAD_SHELL_COMMAND,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteThread",
      method: protocol.METHOD_THREAD_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "startThreadCompaction",
      method: protocol.METHOD_THREAD_COMPACT_START,
      kind: "request",
      params: "required",
    },
    {
      name: "resumeThread",
      method: protocol.METHOD_THREAD_RESUME,
      kind: "request",
      params: "required",
    },
    {
      name: "listAgentSessionFileCheckpoints",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "getAgentSessionFileCheckpoint",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "diffAgentSessionFileCheckpoint",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_DIFF,
      kind: "request",
      params: "required",
    },
    {
      name: "restoreAgentSessionFileCheckpoint",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_RESTORE,
      kind: "request",
      params: "required",
    },
    {
      name: "getOrCreateSessionFile",
      method: protocol.METHOD_SESSION_FILE_GET_OR_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateSessionFileMeta",
      method: protocol.METHOD_SESSION_FILE_UPDATE_META,
      kind: "request",
      params: "required",
    },
    {
      name: "saveSessionFile",
      method: protocol.METHOD_SESSION_FILE_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "readSessionFile",
      method: protocol.METHOD_SESSION_FILE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveSessionFilePath",
      method: protocol.METHOD_SESSION_FILE_RESOLVE_PATH,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteSessionFile",
      method: protocol.METHOD_SESSION_FILE_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "listSessionFiles",
      method: protocol.METHOD_SESSION_FILE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaces",
      method: protocol.METHOD_WORKSPACE_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readWorkspace",
      method: protocol.METHOD_WORKSPACE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "updateWorkspace",
      method: protocol.METHOD_WORKSPACE_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteWorkspace",
      method: protocol.METHOD_WORKSPACE_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "ensureWorkspace",
      method: protocol.METHOD_WORKSPACE_ENSURE,
      kind: "request",
      params: "required",
    },
    {
      name: "readWorkspaceByPath",
      method: protocol.METHOD_WORKSPACE_BY_PATH_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "readDefaultWorkspace",
      method: protocol.METHOD_WORKSPACE_DEFAULT_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "ensureDefaultWorkspace",
      method: protocol.METHOD_WORKSPACE_DEFAULT_ENSURE,
      kind: "request",
      params: "none",
    },
    {
      name: "readWorkspaceProjectsRoot",
      method: protocol.METHOD_WORKSPACE_PROJECTS_ROOT_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "resolveWorkspaceProjectPath",
      method: protocol.METHOD_WORKSPACE_PROJECT_PATH_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "ensureWorkspaceReady",
      method: protocol.METHOD_WORKSPACE_ENSURE_READY,
      kind: "request",
      params: "required",
    },
    {
      name: "requestWorkspaceRightSurface",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_REQUEST,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaceRightSurfacePending",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "consumeWorkspaceRightSurfacePending",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_CONSUME,
      kind: "request",
      params: "required",
    },
    {
      name: "dismissWorkspaceRightSurfacePending",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_DISMISS,
      kind: "request",
      params: "required",
    },
    {
      name: "listApps",
      method: protocol.METHOD_APP_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readApps",
      method: protocol.METHOD_APP_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listInstalledApps",
      method: protocol.METHOD_APP_INSTALLED,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "listSkills",
      method: protocol.METHOD_SKILLS_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "setSkillsExtraRoots",
      method: protocol.METHOD_SKILLS_EXTRA_ROOTS_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "writeSkillsConfig",
      method: protocol.METHOD_SKILLS_CONFIG_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "listHooks",
      method: protocol.METHOD_HOOKS_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readSkill",
      method: protocol.METHOD_SKILL_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listManagementSkills",
      method: protocol.METHOD_SKILL_MANAGEMENT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "installManagementSkill",
      method: protocol.METHOD_SKILL_MANAGEMENT_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "uninstallManagementSkill",
      method: protocol.METHOD_SKILL_MANAGEMENT_UNINSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listSkillRepositories",
      method: protocol.METHOD_SKILL_REPOSITORY_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "saveSkillRepository",
      method: protocol.METHOD_SKILL_REPOSITORY_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteSkillRepository",
      method: protocol.METHOD_SKILL_REPOSITORY_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "refreshSkillCache",
      method: protocol.METHOD_SKILL_CACHE_REFRESH,
      kind: "request",
      params: "none",
    },
    {
      name: "listInstalledSkillDirectories",
      method: protocol.METHOD_SKILL_INSTALLED_DIRECTORIES_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "inspectLocalSkill",
      method: protocol.METHOD_SKILL_LOCAL_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectLocalSkillDetail",
      method: protocol.METHOD_SKILL_LOCAL_DETAIL_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "createSkillScaffold",
      method: protocol.METHOD_SKILL_LOCAL_SCAFFOLD_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "importLocalSkill",
      method: protocol.METHOD_SKILL_LOCAL_IMPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "renameLocalSkill",
      method: protocol.METHOD_SKILL_LOCAL_RENAME,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectRemoteSkill",
      method: protocol.METHOD_SKILL_REMOTE_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectLocalSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_LOCAL_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "installLocalSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_LOCAL_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "replaceLocalSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_LOCAL_REPLACE,
      kind: "request",
      params: "required",
    },
    {
      name: "exportSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "installMarketplaceSkill",
      method: protocol.METHOD_SKILL_MARKETPLACE_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "installSkillFromDownload",
      method: protocol.METHOD_SKILL_PACKAGE_DOWNLOAD_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaceSkillBindings",
      method: protocol.METHOD_WORKSPACE_SKILL_BINDINGS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaceRegisteredSkills",
      method: protocol.METHOD_WORKSPACE_REGISTERED_SKILLS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "setPluginCatalogEnabled",
      method: protocol.METHOD_PLUGIN_ENABLED_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "listPluginCatalog",
      method: protocol.METHOD_PLUGIN_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "searchPlugins",
      method: protocol.METHOD_PLUGIN_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "readPluginCatalog",
      method: protocol.METHOD_PLUGIN_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "installPluginCatalog",
      method: protocol.METHOD_PLUGIN_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "uninstallPluginCatalog",
      method: protocol.METHOD_PLUGIN_UNINSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listInstalledPluginCatalog",
      method: protocol.METHOD_PLUGIN_INSTALLED,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "listKnowledgePacks",
      method: protocol.METHOD_KNOWLEDGE_PACK_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readKnowledgePack",
      method: protocol.METHOD_KNOWLEDGE_PACK_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "importKnowledgeSource",
      method: protocol.METHOD_KNOWLEDGE_SOURCE_IMPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "compileKnowledgePack",
      method: protocol.METHOD_KNOWLEDGE_PACK_COMPILE,
      kind: "request",
      params: "required",
    },
    {
      name: "setDefaultKnowledgePack",
      method: protocol.METHOD_KNOWLEDGE_PACK_DEFAULT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "updateKnowledgePackStatus",
      method: protocol.METHOD_KNOWLEDGE_PACK_STATUS_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveKnowledgeContext",
      method: protocol.METHOD_KNOWLEDGE_CONTEXT_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "validateKnowledgeContextRun",
      method: protocol.METHOD_KNOWLEDGE_CONTEXT_RUN_VALIDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpServers",
      method: protocol.METHOD_MCP_SERVER_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "listMcpServersWithStatus",
      method: protocol.METHOD_MCP_SERVER_STATUS_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "createMcpServer",
      method: protocol.METHOD_MCP_SERVER_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateMcpServer",
      method: protocol.METHOD_MCP_SERVER_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteMcpServer",
      method: protocol.METHOD_MCP_SERVER_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "setMcpServerEnabled",
      method: protocol.METHOD_MCP_SERVER_ENABLED_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "importMcpServersFromApp",
      method: protocol.METHOD_MCP_SERVER_IMPORT_FROM_APP,
      kind: "request",
      params: "required",
    },
    {
      name: "syncAllMcpServersToLive",
      method: protocol.METHOD_MCP_SERVER_SYNC_ALL_TO_LIVE,
      kind: "request",
      params: "none",
    },
    {
      name: "loginMcpServerOauth",
      method: protocol.METHOD_MCP_SERVER_OAUTH_LOGIN,
      kind: "request",
      params: "required",
    },
    {
      name: "logoutMcpServerOauth",
      method: protocol.METHOD_MCP_SERVER_OAUTH_LOGOUT,
      kind: "request",
      params: "required",
    },
    {
      name: "startMcpServer",
      method: protocol.METHOD_MCP_SERVER_START,
      kind: "request",
      params: "required",
    },
    {
      name: "stopMcpServer",
      method: protocol.METHOD_MCP_SERVER_STOP,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpTools",
      method: protocol.METHOD_MCP_TOOL_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "listMcpToolsForContext",
      method: protocol.METHOD_MCP_TOOL_LIST_FOR_CONTEXT,
      kind: "request",
      params: "required",
    },
    {
      name: "searchMcpTools",
      method: protocol.METHOD_MCP_TOOL_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "callMcpServerTool",
      method: protocol.METHOD_MCP_SERVER_TOOL_CALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpPrompts",
      method: protocol.METHOD_MCP_PROMPT_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "getMcpPrompt",
      method: protocol.METHOD_MCP_PROMPT_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpResources",
      method: protocol.METHOD_MCP_RESOURCE_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readMcpServerResource",
      method: protocol.METHOD_MCP_SERVER_RESOURCE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "subscribeMcpResource",
      method: protocol.METHOD_MCP_RESOURCE_SUBSCRIBE,
      kind: "request",
      params: "required",
    },
    {
      name: "unsubscribeMcpResource",
      method: protocol.METHOD_MCP_RESOURCE_UNSUBSCRIBE,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectMemory",
      method: protocol.METHOD_PROJECT_MEMORY_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "searchMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "addMemoryStoreNote",
      method: protocol.METHOD_MEMORY_STORE_ADD_NOTE,
      kind: "request",
      params: "required",
    },
    {
      name: "consolidateMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_CONSOLIDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "listMemoryStoreReviewNotes",
      method: protocol.METHOD_MEMORY_STORE_REVIEW_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveMemoryStoreReviewNote",
      method: protocol.METHOD_MEMORY_STORE_REVIEW_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "healthMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_HEALTH,
      kind: "request",
      params: "required",
    },
    {
      name: "resetMemory",
      method: protocol.METHOD_MEMORY_RESET,
      kind: "request",
      params: "omitted",
    },
    {
      name: "rebuildMemoryStoreIndex",
      method: protocol.METHOD_MEMORY_STORE_INDEX_REBUILD,
      kind: "request",
      params: "required",
    },
    {
      name: "listLogs",
      method: protocol.METHOD_LOG_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readPersistedLogTail",
      method: protocol.METHOD_LOG_PERSISTED_TAIL,
      kind: "request",
      params: "required",
    },
    {
      name: "clearLogs",
      method: protocol.METHOD_LOG_CLEAR,
      kind: "request",
      params: "none",
    },
    {
      name: "clearDiagnosticLogHistory",
      method: protocol.METHOD_LOG_DIAGNOSTIC_HISTORY_CLEAR,
      kind: "request",
      params: "none",
    },
    {
      name: "readLogStorageDiagnostics",
      method: protocol.METHOD_DIAGNOSTICS_LOG_STORAGE_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "exportSupportBundle",
      method: protocol.METHOD_DIAGNOSTICS_SUPPORT_BUNDLE_EXPORT,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readServerDiagnostics",
      method: protocol.METHOD_DIAGNOSTICS_SERVER_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "readWindowsStartupDiagnostics",
      method: protocol.METHOD_DIAGNOSTICS_WINDOWS_STARTUP_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "listDiagnosticsTraces",
      method: protocol.METHOD_DIAGNOSTICS_TRACE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readDiagnosticsTrace",
      method: protocol.METHOD_DIAGNOSTICS_TRACE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "exportDiagnosticsTrace",
      method: protocol.METHOD_DIAGNOSTICS_TRACE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "readGatewayChannelStatus",
      method: protocol.METHOD_GATEWAY_CHANNEL_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "startGatewayChannel",
      method: protocol.METHOD_GATEWAY_CHANNEL_START,
      kind: "request",
      params: "required",
    },
    {
      name: "stopGatewayChannel",
      method: protocol.METHOD_GATEWAY_CHANNEL_STOP,
      kind: "request",
      params: "required",
    },
    {
      name: "probeTelegramChannel",
      method: protocol.METHOD_TELEGRAM_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "probeFeishuChannel",
      method: protocol.METHOD_FEISHU_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "probeDiscordChannel",
      method: protocol.METHOD_DISCORD_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "probeWechatChannel",
      method: protocol.METHOD_WECHAT_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "startWechatChannelLogin",
      method: protocol.METHOD_WECHAT_CHANNEL_LOGIN_START,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "waitWechatChannelLogin",
      method: protocol.METHOD_WECHAT_CHANNEL_LOGIN_WAIT,
      kind: "request",
      params: "required",
    },
    {
      name: "listWechatChannelAccounts",
      method: protocol.METHOD_WECHAT_CHANNEL_ACCOUNT_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "removeWechatChannelAccount",
      method: protocol.METHOD_WECHAT_CHANNEL_ACCOUNT_REMOVE,
      kind: "request",
      params: "required",
    },
    {
      name: "setWechatChannelRuntimeModel",
      method: protocol.METHOD_WECHAT_CHANNEL_RUNTIME_MODEL_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "probeGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_PROBE,
      kind: "request",
      params: "none",
    },
    {
      name: "detectGatewayTunnelCloudflared",
      method: protocol.METHOD_GATEWAY_TUNNEL_CLOUDFLARED_DETECT,
      kind: "request",
      params: "none",
    },
    {
      name: "installGatewayTunnelCloudflared",
      method: protocol.METHOD_GATEWAY_TUNNEL_CLOUDFLARED_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "createGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "startGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_START,
      kind: "request",
      params: "none",
    },
    {
      name: "stopGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_STOP,
      kind: "request",
      params: "none",
    },
    {
      name: "restartGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_RESTART,
      kind: "request",
      params: "none",
    },
    {
      name: "readGatewayTunnelStatus",
      method: protocol.METHOD_GATEWAY_TUNNEL_STATUS,
      kind: "request",
      params: "none",
    },
    {
      name: "syncGatewayTunnelWebhookUrl",
      method: protocol.METHOD_GATEWAY_TUNNEL_SYNC_WEBHOOK_URL,
      kind: "request",
      params: "required",
    },
    {
      name: "createImageMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_IMAGE_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createAudioMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_AUDIO_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createTranscriptionMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_TRANSCRIPTION_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createVideoMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_VIDEO_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "completeImageMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_IMAGE_COMPLETE,
      kind: "request",
      params: "required",
    },
    {
      name: "completeAudioMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_AUDIO_COMPLETE,
      kind: "request",
      params: "required",
    },
    {
      name: "getMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "listMediaTaskArtifacts",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "cancelMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_CANCEL,
      kind: "request",
      params: "required",
    },
    {
      name: "getGalleryMaterial",
      method: protocol.METHOD_GALLERY_MATERIAL_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "createGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "getGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "updateGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "listGalleryMaterialsByImageCategory",
      method: protocol.METHOD_GALLERY_MATERIAL_LIST_BY_IMAGE_CATEGORY,
      kind: "request",
      params: "required",
    },
    {
      name: "listGalleryMaterialsByLayoutCategory",
      method: protocol.METHOD_GALLERY_MATERIAL_LIST_BY_LAYOUT_CATEGORY,
      kind: "request",
      params: "required",
    },
    {
      name: "listGalleryMaterialsByMood",
      method: protocol.METHOD_GALLERY_MATERIAL_LIST_BY_MOOD,
      kind: "request",
      params: "required",
    },
    {
      name: "listProjectMaterials",
      method: protocol.METHOD_PROJECT_MATERIAL_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "getProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "countProjectMaterials",
      method: protocol.METHOD_PROJECT_MATERIAL_COUNT,
      kind: "request",
      params: "required",
    },
    {
      name: "uploadProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_UPLOAD,
      kind: "request",
      params: "required",
    },
    {
      name: "importProjectMaterialFromUrl",
      method: protocol.METHOD_PROJECT_MATERIAL_IMPORT_FROM_URL,
      kind: "request",
      params: "required",
    },
    {
      name: "updateProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectMaterialContent",
      method: protocol.METHOD_PROJECT_MATERIAL_CONTENT,
      kind: "request",
      params: "required",
    },
    {
      name: "listVoiceAsrCredentials",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "createVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "setDefaultVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_DEFAULT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "testVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_TEST,
      kind: "request",
      params: "required",
    },
    {
      name: "listVoiceInstructions",
      method: protocol.METHOD_VOICE_INSTRUCTION_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "saveVoiceInstruction",
      method: protocol.METHOD_VOICE_INSTRUCTION_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteVoiceInstruction",
      method: protocol.METHOD_VOICE_INSTRUCTION_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "setDefaultVoiceModel",
      method: protocol.METHOD_VOICE_MODEL_DEFAULT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "testTranscribeVoiceModelFile",
      method: protocol.METHOD_VOICE_MODEL_TEST_TRANSCRIBE_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "transcribeVoiceAudio",
      method: protocol.METHOD_VOICE_TRANSCRIPTION_TRANSCRIBE_AUDIO,
      kind: "request",
      params: "required",
    },
    {
      name: "polishVoiceText",
      method: protocol.METHOD_VOICE_TRANSCRIPTION_POLISH_TEXT,
      kind: "request",
      params: "required",
    },
    {
      name: "readUsageStats",
      method: protocol.METHOD_USAGE_STATS_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listUsageStatsModelRanking",
      method: protocol.METHOD_USAGE_STATS_MODEL_RANKING_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listUsageStatsDailyTrends",
      method: protocol.METHOD_USAGE_STATS_DAILY_TRENDS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readArtifacts",
      method: protocol.METHOD_ARTIFACT_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "writeArtifact",
      method: protocol.METHOD_ARTIFACT_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "searchFiles",
      method: protocol.METHOD_FUZZY_FILE_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "readFile",
      method: protocol.METHOD_FS_READ_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "writeFile",
      method: protocol.METHOD_FS_WRITE_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "createDirectory",
      method: protocol.METHOD_FS_CREATE_DIRECTORY,
      kind: "request",
      params: "required",
    },
    {
      name: "getMetadata",
      method: protocol.METHOD_FS_GET_METADATA,
      kind: "request",
      params: "required",
    },
    {
      name: "readDirectory",
      method: protocol.METHOD_FS_READ_DIRECTORY,
      kind: "request",
      params: "required",
    },
    {
      name: "remove",
      method: protocol.METHOD_FS_REMOVE,
      kind: "request",
      params: "required",
    },
    {
      name: "copy",
      method: protocol.METHOD_FS_COPY,
      kind: "request",
      params: "required",
    },
    {
      name: "watch",
      method: protocol.METHOD_FS_WATCH,
      kind: "request",
      params: "required",
    },
    {
      name: "unwatch",
      method: protocol.METHOD_FS_UNWATCH,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectGitStatus",
      method: protocol.METHOD_PROJECT_GIT_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectGitDiff",
      method: protocol.METHOD_PROJECT_GIT_DIFF,
      kind: "request",
      params: "required",
    },
    {
      name: "listProjectGitCommits",
      method: protocol.METHOD_PROJECT_GIT_COMMITS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "checkoutProjectGitBranch",
      method: protocol.METHOD_PROJECT_GIT_BRANCH_CHECKOUT,
      kind: "request",
      params: "required",
    },
    {
      name: "createProjectGitBranch",
      method: protocol.METHOD_PROJECT_GIT_BRANCH_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createProjectGitWorktree",
      method: protocol.METHOD_PROJECT_GIT_WORKTREE_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "exportHandoffBundle",
      method: protocol.METHOD_AGENT_SESSION_HANDOFF_BUNDLE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportReplayCase",
      method: protocol.METHOD_AGENT_SESSION_REPLAY_CASE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportAnalysisHandoff",
      method: protocol.METHOD_AGENT_SESSION_ANALYSIS_HANDOFF_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportReviewDecisionTemplate",
      method: protocol.METHOD_AGENT_SESSION_REVIEW_DECISION_TEMPLATE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "saveReviewDecision",
      method: protocol.METHOD_AGENT_SESSION_REVIEW_DECISION_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "startSession",
      method: protocol.METHOD_THREAD_START,
      kind: "request",
      params: "required",
    },
    {
      name: "forkThread",
      method: protocol.METHOD_THREAD_FORK,
      kind: "request",
      params: "required",
    },
    {
      name: "readSession",
      method: protocol.METHOD_THREAD_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "readWorkflow",
      method: protocol.METHOD_WORKFLOW_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "cancelWorkflow",
      method: protocol.METHOD_WORKFLOW_CANCEL,
      kind: "request",
      params: "required",
    },
    {
      name: "retryWorkflow",
      method: protocol.METHOD_WORKFLOW_RETRY,
      kind: "request",
      params: "required",
    },
    {
      name: "respondWorkflow",
      method: protocol.METHOD_WORKFLOW_RESPOND,
      kind: "request",
      params: "required",
    },
    {
      name: "readAgentSessionToolInventory",
      method: protocol.METHOD_AGENT_SESSION_TOOL_INVENTORY_READ,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readMedia",
      method: protocol.METHOD_MEDIA_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "readConfig",
      method: protocol.METHOD_CONFIG_READ,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "writeConfigValue",
      method: protocol.METHOD_CONFIG_VALUE_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "writeConfigBatch",
      method: protocol.METHOD_CONFIG_BATCH_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "listCollaborationModes",
      method: protocol.METHOD_COLLABORATION_MODE_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "listExperimentalFeatures",
      method: protocol.METHOD_EXPERIMENTAL_FEATURE_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "setExperimentalFeatureEnablement",
      method: protocol.METHOD_EXPERIMENTAL_FEATURE_ENABLEMENT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "listPermissionProfiles",
      method: protocol.METHOD_PERMISSION_PROFILE_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readWindowsSandboxReadiness",
      method: protocol.METHOD_WINDOWS_SANDBOX_READINESS,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "startWindowsSandboxSetup",
      method: protocol.METHOD_WINDOWS_SANDBOX_SETUP_START,
      kind: "request",
      params: "required",
    },
    {
      name: "listModels",
      method: protocol.METHOD_MODEL_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readModelProviderCapabilities",
      method: protocol.METHOD_MODEL_PROVIDER_CAPABILITIES_READ,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "addEnvironment",
      method: protocol.METHOD_ENVIRONMENT_ADD,
      kind: "request",
      params: "required",
    },
    {
      name: "readEnvironmentInfo",
      method: protocol.METHOD_ENVIRONMENT_INFO,
      kind: "request",
      params: "required",
    },
    {
      name: "readEnvironmentStatus",
      method: protocol.METHOD_ENVIRONMENT_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "listModelPreferences",
      method: protocol.METHOD_MODEL_PREFERENCES_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readModelSyncState",
      method: protocol.METHOD_MODEL_SYNC_STATE_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "listModelProviders",
      method: protocol.METHOD_MODEL_PROVIDER_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "listModelProviderCatalog",
      method: protocol.METHOD_MODEL_PROVIDER_CATALOG_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "createModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateModelProviderSortOrders",
      method: protocol.METHOD_MODEL_PROVIDER_SORT_ORDERS_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "exportModelProviderConfig",
      method: protocol.METHOD_MODEL_PROVIDER_CONFIG_EXPORT,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "importModelProviderConfig",
      method: protocol.METHOD_MODEL_PROVIDER_CONFIG_IMPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "testModelProviderConnection",
      method: protocol.METHOD_MODEL_PROVIDER_TEST_CONNECTION,
      kind: "request",
      params: "required",
    },
    {
      name: "testModelProviderChat",
      method: protocol.METHOD_MODEL_PROVIDER_TEST_CHAT,
      kind: "request",
      params: "required",
    },
    {
      name: "fetchModelProviderModels",
      method: protocol.METHOD_MODEL_PROVIDER_FETCH_MODELS,
      kind: "request",
      params: "required",
    },
    {
      name: "createModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "readModelProviderUiState",
      method: protocol.METHOD_MODEL_PROVIDER_UI_STATE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "writeModelProviderUiState",
      method: protocol.METHOD_MODEL_PROVIDER_UI_STATE_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "readModelProviderAlias",
      method: protocol.METHOD_MODEL_PROVIDER_ALIAS_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listModelProviderAliases",
      method: protocol.METHOD_MODEL_PROVIDER_ALIAS_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "resolveConnectDeepLink",
      method: protocol.METHOD_CONNECT_DEEP_LINK_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveConnectOpenDeepLink",
      method: protocol.METHOD_CONNECT_OPEN_DEEP_LINK_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "saveConnectRelayApiKey",
      method: protocol.METHOD_CONNECT_RELAY_API_KEY_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "sendConnectCallback",
      method: protocol.METHOD_CONNECT_CALLBACK_SEND,
      kind: "request",
      params: "required",
    },
    {
      name: "scanConversationImportSource",
      method: protocol.METHOD_CONVERSATION_IMPORT_SOURCE_SCAN,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "previewConversationImportThread",
      method: protocol.METHOD_CONVERSATION_IMPORT_THREAD_PREVIEW,
      kind: "request",
      params: "required",
    },
    {
      name: "commitConversationImportThread",
      method: protocol.METHOD_CONVERSATION_IMPORT_THREAD_COMMIT,
      kind: "request",
      params: "required",
    },
    {
      name: "readConversationImportJob",
      method: protocol.METHOD_CONVERSATION_IMPORT_JOB_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "spawnProcess",
      method: protocol.METHOD_PROCESS_SPAWN,
      kind: "request",
      params: "required",
    },
    {
      name: "writeProcessStdin",
      method: protocol.METHOD_PROCESS_WRITE_STDIN,
      kind: "request",
      params: "required",
    },
    {
      name: "resizeProcessPty",
      method: protocol.METHOD_PROCESS_RESIZE_PTY,
      kind: "request",
      params: "required",
    },
    {
      name: "killProcess",
      method: protocol.METHOD_PROCESS_KILL,
      kind: "request",
      params: "required",
    },
    {
      name: "execCommand",
      method: protocol.METHOD_COMMAND_EXEC,
      kind: "request",
      params: "required",
    },
    {
      name: "writeCommandExec",
      method: protocol.METHOD_COMMAND_EXEC_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "resizeCommandExec",
      method: protocol.METHOD_COMMAND_EXEC_RESIZE,
      kind: "request",
      params: "required",
    },
    {
      name: "terminateCommandExec",
      method: protocol.METHOD_COMMAND_EXEC_TERMINATE,
      kind: "request",
      params: "required",
    },
    {
      name: "startTurn",
      method: protocol.METHOD_TURN_START,
      kind: "request",
      params: "required",
    },
    {
      name: "startReview",
      method: protocol.METHOD_REVIEW_START,
      kind: "request",
      params: "required",
    },
    {
      name: "steerTurn",
      method: protocol.METHOD_TURN_STEER,
      kind: "request",
      params: "required",
    },
    {
      name: "cancelTurn",
      method: protocol.METHOD_TURN_INTERRUPT,
      kind: "request",
      params: "required",
    },
    {
      name: "respondAction",
      method: protocol.METHOD_AGENT_SESSION_ACTION_RESPOND,
      kind: "request",
      params: "required",
    },
  ];

function resolveParams(
  mode: RequestClientParamsMode,
  args: IArguments,
): unknown {
  if (mode === "omitted") {
    return undefined;
  }
  if (mode === "none") {
    return {};
  }
  if (mode === "optional-empty") {
    return args.length === 0 || args[0] === undefined ? {} : args[0];
  }
  return args[0];
}

export function installAppServerRequestClientMethods(
  prototype: AppServerClient,
): void {
  for (const spec of APP_SERVER_REQUEST_CLIENT_METHODS) {
    Object.defineProperty(prototype, spec.name, {
      configurable: true,
      writable: true,
      value: function (
        this: AppServerClient,
      ): protocol.JsonRpcRequest | protocol.JsonRpcNotification {
        const params = resolveParams(spec.params, arguments);
        if (spec.kind === "notification") {
          return protocol.notification(spec.method, params);
        }
        return this.request(spec.method, params);
      },
    });
  }
}
